repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-json                          # Attempts to load all json files to verify syntax
    -   id: check-yaml                          # Checks yaml files for parseable syntax
    -   id: check-added-large-files             # Prevent giant files from being committed
    -   id: check-merge-conflict                # Check for files that contain merge conflict strings
    -   id: end-of-file-fixer                   # Ensures that a file is either empty, or ends with one newline
        exclude:
            requirements.txt
    -   id: fix-encoding-pragma                 # Add # -*- coding: utf-8 -*- to the top of python files
    -   id: mixed-line-ending                   # Replaces or checks mixed line ending
    -   id: trailing-whitespace                 # Trims trailing whitespace
    -   id: pretty-format-json                  # Checks that all your JSON files are "pretty" (keys sorted and indented)
    -   id: requirements-txt-fixer              # Sorts entries in requirements.txt
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black                               # Python code formatter
        args: [-l 88]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort                               # Sort and organize Python imports
        args: [ --multi-line=3 , --trailing-comma , --line-length=88, --use-parentheses, --profile=black]
-   repo: https://github.com/roy-ht/pre-commit-jupyter
    rev: v1.2.1
    hooks:
    -   id: jupyter-notebook-cleanup
        args:
            # - --remove-kernel-metadata
            - --pin-patterns
            - "[pin];[donotremove]"
