repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml                          # Checks yaml files for parseable syntax
    -   id: check-added-large-files             # Prevent giant files from being committed
    -   id: check-merge-conflict                # Check for files that contain merge conflict strings
    -   id: end-of-file-fixer                   # Ensures that a file is either empty, or ends with one newline
        exclude:
            requirements.txt
    -   id: fix-encoding-pragma                 # Add # -*- coding: utf-8 -*- to the top of python files
    -   id: mixed-line-ending                   # Replaces or checks mixed line ending
    -   id: trailing-whitespace                 # Trims trailing whitespace
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black                               # Python code formatter
-   repo: https://github.com/timothycrosley/isort
    rev: 5.4.2
    hooks:
    -   id: isort                               # Sort and organize Python imports
        args: [ -m=3 , -tc , -l 100 ]
