# -*- coding: utf-8 -*-
import pathlib

PROJECT_FOLDER_PATH = pathlib.Path(__file__).parent.parent.resolve()
TRAINED_MODELS_FOLDER_PATH = PROJECT_FOLDER_PATH / "trained_models"
MODEL_PERFORMANCE_FOLDER_PATH = PROJECT_FOLDER_PATH / "model_performance"

TSP_TRAIN_DATASET_FOLDER_PATH = PROJECT_FOLDER_PATH / "data/tsp/dataset/train"
TSP_TEST_DATASET_FOLDER_PATH = PROJECT_FOLDER_PATH / "data/tsp/dataset/test"
TSP_VAL_DATASET_FOLDER_PATH = PROJECT_FOLDER_PATH / "data/tsp/dataset/val"
DTSP_TRAIN_DATASET_FOLDER_PATH = PROJECT_FOLDER_PATH / "data/dtsp/dataset/train"
DTSP_TEST_DATASET_FOLDER_PATH = PROJECT_FOLDER_PATH / "data/dtsp/dataset/test"
DTSP_VAL_DATASET_FOLDER_PATH = PROJECT_FOLDER_PATH / "data/dtsp/dataset/val"

TSP_TRAIN_PREDICTIONS_FOLDER_PATH = PROJECT_FOLDER_PATH / "data/tsp/predictions/train"
TSP_TEST_PREDICTIONS_FOLDER_PATH = PROJECT_FOLDER_PATH / "data/tsp/predictions/test"
DTSP_TRAIN_PREDICTIONS_FOLDER_PATH = PROJECT_FOLDER_PATH / "data/dtsp/predictions/train"
DTSP_TEST_PREDICTIONS_FOLDER_PATH = PROJECT_FOLDER_PATH / "data/dtsp/predictions/test"

folder_path_list = [
    PROJECT_FOLDER_PATH,
    TRAINED_MODELS_FOLDER_PATH,
    MODEL_PERFORMANCE_FOLDER_PATH,
    TSP_TRAIN_DATASET_FOLDER_PATH,
    TSP_TEST_DATASET_FOLDER_PATH,
    TSP_VAL_DATASET_FOLDER_PATH,
    DTSP_TRAIN_DATASET_FOLDER_PATH,
    DTSP_TEST_DATASET_FOLDER_PATH,
    DTSP_VAL_DATASET_FOLDER_PATH,
    TSP_TRAIN_PREDICTIONS_FOLDER_PATH,
    TSP_TEST_PREDICTIONS_FOLDER_PATH,
    DTSP_TRAIN_PREDICTIONS_FOLDER_PATH,
    DTSP_TEST_PREDICTIONS_FOLDER_PATH,
]

# create all folders that do not exist yet
for folder_path in folder_path_list:
    folder_path.mkdir(parents=True, exist_ok=True)
